### ISSUE TITLE
[BUG] koordlet panic with GPU feature

### ISSUE THREAD

**Issue by eahydra** [koordinator-sh/koordinator#1062]
**What happened**:

Koordlet panic with feature-gate `Accelerators`  on GPU nodes. 

```go panic
I0227 14:18:29.409907   47983 cpu_suppress.go:584] calculated BE suppress policy: cpuset [0 48 24 72 1 49 25 73 2 50 26 74 3 51 27 75 4 52 28 76 5 53 29 77 6 54 30 78 7 55 31 79 8 56 32 80 9 57 33 81 10 58 34 82 11 59 35 83 12 60 36 84 13 61 37 85 14 62 38 86 15]
I0227 14:18:29.414465   47983 cpu_suppress.go:360] suppressBECPU finished, suppress be cpu successfully: current cpuset [0 48 24 72 1 49 25 73 2 50 26 74 3 51 27 75 4 52 28 76 5 53 29 77 6 54 30 78 7 55 31 79 8 56 32 80 9 57 33 81 10 58 34 82 11 59 35 83 12 60 36 84 13 61 37 85 14 62 38 86 15]
E0227 14:18:29.626656   47983 runtime.go:78] Observed a panic: runtime.boundsError{x:1, y:1, signed:true, code:0x0} (runtime error: index out of range [1] with length 1)
goroutine 349 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x21fbe40, 0xc001c70510})
	/go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/runtime/runtime.go:74 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x10117c1e0})
	/go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/runtime/runtime.go:48 +0x75
panic({0x21fbe40, 0xc001c70510})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/koordinator-sh/koordinator/pkg/koordlet/metricsadvisor.(*gpuDeviceManager).collectGPUUsage(0xc001024000)
	/go/src/github.com/koordinator-sh/koordinator/pkg/koordlet/metricsadvisor/collector_gpu_linux.go:256 +0x7d1
github.com/koordinator-sh/koordinator/pkg/koordlet/metricsadvisor.(*collector).collectGPUUsage(...)
	/go/src/github.com/koordinator-sh/koordinator/pkg/koordlet/metricsadvisor/collector_gpu.go:54
github.com/koordinator-sh/koordinator/pkg/koordlet/metricsadvisor.(*collector).Run.func1()
	/go/src/github.com/koordinator-sh/koordinator/pkg/koordlet/metricsadvisor/collector.go:126 +0x51
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000639f00)
	/go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000f047d0, {0x26fdc20, 0xc0013c9c80}, 0x1, 0xc000d04000)
	/go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00018e660, 0x3b9aca00, 0x0, 0x0, 0x4535a5)
	/go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x0, 0xc00022cf68, 0xc00022cf78)
	/go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/wait/wait.go:90 +0x25
created by github.com/koordinator-sh/koordinator/pkg/koordlet/metricsadvisor.(*collector).Run
	/go/src/github.com/koordinator-sh/koordinator/pkg/koordlet/metricsadvisor/collector.go:125 +0x3cf
panic: runtime error: index out of range [1] with length 1 [recovered]
	panic: runtime error: index out of range [1] with length 1

goroutine 349 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x10117c1e0})
	/go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/runtime/runtime.go:55 +0xd8
panic({0x21fbe40, 0xc001c70510})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/koordinator-sh/koordinator/pkg/koordlet/metricsadvisor.(*gpuDeviceManager).collectGPUUsage(0xc001024000)
	/go/src/github.com/koordinator-sh/koordinator/pkg/koordlet/metricsadvisor/collector_gpu_linux.go:256 +0x7d1
github.com/koordinator-sh/koordinator/pkg/koordlet/metricsadvisor.(*collector).collectGPUUsage(...)
	/go/src/github.com/koordinator-sh/koordinator/pkg/koordlet/metricsadvisor/collector_gpu.go:54
github.com/koordinator-sh/koordinator/pkg/koordlet/metricsadvisor.(*collector).Run.func1()
	/go/src/github.com/koordinator-sh/koordinator/pkg/koordlet/metricsadvisor/collector.go:126 +0x51
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000639f00)
	/go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000f047d0, {0x26fdc20, 0xc0013c9c80}, 0x1, 0xc000d04000)
	/go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00018e660, 0x3b9aca00, 0x0, 0x0, 0x4535a5)
	/go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x0, 0xc00022cf68, 0xc00022cf78)
	/go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/wait/wait.go:90 +0x25
created by github.com/koordinator-sh/koordinator/pkg/koordlet/metricsadvisor.(*collector).Run
	/go/src/github.com/koordinator-sh/koordinator/pkg/koordlet/metricsadvisor/collector.go:125 +0x3cf
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

koordlet prints the log with configuration as following:

```log
I0227 14:12:16.211646   47983 resctrl.go:64] isResctrlAvailableByCpuInfo result, isCatFlagSet: true, isMbaFlagSet: true
I0227 14:12:16.211794   47983 resctrl.go:75] isResctrlAvailableByKernelCmd result,isCatFlagSet: false,isMbaFlagSet: false
I0227 14:12:16.240164   47983 feature_gate.go:245] feature gates: &{map[Accelerators:true AllAlpha:true AllBeta:true AuditEvents:true AuditEventsHTTPHandler:true BECPUEvict:true BECPUSuppress:true BEMemoryEvict:true BatchResource:true CPICollector:true CPUBurst:true CPUSetAllocator:true CgroupReconcile:true GPUEnvInject:true GroupIdentity:true NodeTopologyReport:true PSICollector:true RdtResctrl:true SystemConfig:true]}
I0227 14:12:16.240460   47983 main.go:70] Setting up client for koordlet
I0227 14:12:16.246850   47983 koordlet.go:75] NODE_NAME is t50a01184.sqa.eu95,start time 1.677478336e+09
I0227 14:12:16.246884   47983 koordlet.go:78] sysconf: &{CgroupRootDir:/host-cgroup/ CgroupKubePath:kubepods/ SysRootDir:/host-sys/ SysFSRootDir:/host-sys-fs/ ProcRootDir:/proc/ VarRunRootDir:/host-var-run/ NodeNameOverride: RuntimeHooksConfigDir:/host-etc-hookserver/ ContainerdEndPoint: DockerEndPoint:},agentMode:dsMode
I0227 14:12:16.246927   47983 koordlet.go:79] kernel version INFO : {IsAnolisOS:true}
```

**Environment**:
- App version:  koordinator v1.1.1
- Kubernetes version (use `kubectl version`):  v1.22
- Install details (e.g. helm install args):   
- Node environment (for koordlet/runtime-proxy issue):
  - Containerd/Docker version: docker://20.10.21
  - OS version:  
  - Kernal version:  4.19.91-013
  - Cgroup driver: cgroupfs/systemd
- Others:

**Comment by jasonliu747** [comment]
duplicate of #904

**Comment by zwzhang0107** [comment]
assign @jasonliu747
