### ISSUE TITLE
[BUG] Panic due to nil pointer dereference in cpusetPlugin with Static cpuManagerPolicy

### ISSUE THREAD

**Issue by chl178** [koordinator-sh/koordinator#1745]
**What happened**:
```
I1115 15:02:14.222412   18820 rule.go:102] get empty cpuset if kubelet is static policy for container cicd/trig-basic-ci-pipeline-run-68l92-git-clone-build-and-push-pod/
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1a74d4e]

goroutine 439 [running]:
github.com/koordinator-sh/koordinator/pkg/koordlet/runtimehooks/hooks/cpuset.(*cpusetPlugin).SetContainerCPUSet(0xc00122da50?, {0x28e3000?, 0xc00122da50})
	/go/src/github.com/koordinator-sh/koordinator/pkg/koordlet/runtimehooks/hooks/cpuset/cpuset.go:123 +0x7ce
github.com/koordinator-sh/koordinator/pkg/koordlet/runtimehooks/hooks/cpuset.(*cpusetPlugin).ruleUpdateCb(0xc000878630, {0xc00219e000, 0xa3, 0x2?})
	/go/src/github.com/koordinator-sh/koordinator/pkg/koordlet/runtimehooks/hooks/cpuset/rule.go:164 +0x109
github.com/koordinator-sh/koordinator/pkg/koordlet/runtimehooks/rule.(*Rule).runUpdateCallbacks(0xc000d5c7d0, {0xc00219e000, 0xa3, 0xa3})
	/go/src/github.com/koordinator-sh/koordinator/pkg/koordlet/runtimehooks/rule/rule.go:61 +0xbe
github.com/koordinator-sh/koordinator/pkg/koordlet/runtimehooks/rule.UpdateRules(0x2, {0x23b9440, 0xc002b52420}, {0xc00219e000, 0xa3, 0xa3})
	/go/src/github.com/koordinator-sh/koordinator/pkg/koordlet/runtimehooks/rule/rule.go:100 +0x41c
github.com/koordinator-sh/koordinator/pkg/koordlet/statesinformer/impl.(*callbackRunner).runCallbacks(0xc0001256a0, 0x2, {0x23b9440, 0xc002b52420})
	/go/src/github.com/koordinator-sh/koordinator/pkg/koordlet/statesinformer/impl/callback_runner.go:99 +0x3c3
github.com/koordinator-sh/koordinator/pkg/koordlet/statesinformer/impl.(*callbackRunner).Start.func1()
	/go/src/github.com/koordinator-sh/koordinator/pkg/koordlet/statesinformer/impl/callback_runner.go:114 +0x105
created by github.com/koordinator-sh/koordinator/pkg/koordlet/statesinformer/impl.(*callbackRunner).Start
	/go/src/github.com/koordinator-sh/koordinator/pkg/koordlet/statesinformer/impl/callback_runner.go:106 +0x70
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Set the cpuManagerPolicy  as Static
**Anything else we need to know?**:
In the release-1.3
```
klog.V(5).Infof("get empty cpuset for container %v/%v from rule", *cpusetValue,
			containerCtx.Request.PodMeta.String(), containerCtx.Request.ContainerMeta.Name)
```
If r.kubeletPolicy.Policy == ext.KubeletCPUManagerPolicyStatic
getContainerCPUSet function will return nil of cpusetValue

**Environment**:
- App version: v1.3.0
- Kubernetes version (use `kubectl version`): v1.23.13
- Install details (e.g. helm install args):
- Node environment (for koordlet/runtime-proxy issue):
  - Containerd/Docker version:
  - OS version:
  - Kernal version:
  - Cgroup driver: cgroupfs/systemd
- Others:

**Comment by saintube** [comment]
@chl178 Thanks for your feedback. It is a bug fixed by #1638 and not contained in v1.3.0. Please feel free to cherry-pick the bugfix. It will be soon released in the coming [v1.4](https://github.com/koordinator-sh/koordinator/milestone/12).
