### ISSUE TITLE
[BUG] koordlet panic with GPU machine

### ISSUE THREAD

**Issue by eahydra** [koordinator-sh/koordinator#678]
**What happened**:

koordlet panic

```log
I1008 23:33:56.305750 2220922 collector.go:285] collectPodResUsed finished, pod num 15
E1008 23:33:56.306763 2220922 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 259 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x203d960, 0x3961100})
	/go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/runtime/runtime.go:74 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xfffffffe})
	/go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/runtime/runtime.go:48 +0x75
panic({0x203d960, 0x3961100})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/koordinator-sh/koordinator/pkg/koordlet/statesinformer.(*statesInformer).updateDevice.func1.1(0x0, 0x26fd9c8)
	/go/src/github.com/koordinator-sh/koordinator/pkg/koordlet/statesinformer/states_device_linux.go:102 +0x34
sort.insertionSort_func({0xc00152da00, 0xc001553230}, 0x0, 0x2)
	/usr/local/go/src/sort/zfuncversion.go:12 +0xb1
sort.quickSort_func({0xc00152da00, 0xc001553230}, 0x203000, 0x245c9b0, 0xc00152d9d8)
	/usr/local/go/src/sort/zfuncversion.go:158 +0x185
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- App version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Node environment (for koordlet/runtime-proxy issue):
  - Containerd/Docker version:
  - OS version:
  - Kernal version:
  - Cgroup driver: cgroupfs/systemd
- Others:

**Comment by jasonliu747** [comment]
It's because we update Device CRD in #656. 
Temporary solution would be upgrading Device CRD to the latest version, and restart koordlet.
