### ISSUE TITLE
[BUG] koordlet crash becase  index out of range 

### ISSUE THREAD

**Issue by myl1024** [koordinator-sh/koordinator#904]
We run koordlet in our machine, it crash and report that:
```
I1226 16:44:32.385054   99370 collector_gpu_linux.go:248] Found 5 processes on device 0
E1226 16:44:32.385193   99370 runtime.go:78] Observed a panic: runtime.boundsError{x:1, y:1, signed:true, code:0x0} (runtime error: index out of range [1] with length 1)
goroutine 185 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x21be840, 0xc00077e0a8})
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/runtime/runtime.go:74 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc})
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/runtime/runtime.go:48 +0x75
panic({0x21be840, 0xc00077e0a8})
        /opt/hostedtoolcache/go/1.17.13/x64/src/runtime/panic.go:1038 +0x215
github.com/koordinator-sh/koordinator/pkg/koordlet/metricsadvisor.(*gpuDeviceManager).collectGPUUsage(0xc00099bbc0)
        /home/runner/work/koordinator/koordinator/pkg/koordlet/metricsadvisor/collector_gpu_linux.go:256 +0x7d1
github.com/koordinator-sh/koordinator/pkg/koordlet/metricsadvisor.(*collector).collectGPUUsage(...)
        /home/runner/work/koordinator/koordinator/pkg/koordlet/metricsadvisor/collector_gpu.go:54
github.com/koordinator-sh/koordinator/pkg/koordlet/metricsadvisor.(*collector).Run.func1()
        /home/runner/work/koordinator/koordinator/pkg/koordlet/metricsadvisor/collector.go:134 +0x51
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7fbb28129228)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000172370, {0x26b9600, 0xc00073a4b0}, 0x1, 0xc00013c420)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000184660, 0x3b9aca00, 0x0, 0x0, 0x4537c5)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x0, 0xc000513768, 0xc000513778)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/wait/wait.go:90 +0x25
created by github.com/koordinator-sh/koordinator/pkg/koordlet/metricsadvisor.(*collector).Run
        /home/runner/work/koordinator/koordinator/pkg/koordlet/metricsadvisor/collector.go:133 +0x505
panic: runtime error: index out of range [1] with length 1 [recovered]
        panic: runtime error: index out of range [1] with length 1

goroutine 185 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc})
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/runtime/runtime.go:55 +0xd8
panic({0x21be840, 0xc00077e0a8})
        /opt/hostedtoolcache/go/1.17.13/x64/src/runtime/panic.go:1038 +0x215
github.com/koordinator-sh/koordinator/pkg/koordlet/metricsadvisor.(*gpuDeviceManager).collectGPUUsage(0xc00099bbc0)
        /home/runner/work/koordinator/koordinator/pkg/koordlet/metricsadvisor/collector_gpu_linux.go:256 +0x7d1
github.com/koordinator-sh/koordinator/pkg/koordlet/metricsadvisor.(*collector).collectGPUUsage(...)
        /home/runner/work/koordinator/koordinator/pkg/koordlet/metricsadvisor/collector_gpu.go:54
github.com/koordinator-sh/koordinator/pkg/koordlet/metricsadvisor.(*collector).Run.func1()
        /home/runner/work/koordinator/koordinator/pkg/koordlet/metricsadvisor/collector.go:134 +0x51
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7fbb28129228)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000172370, {0x26b9600, 0xc00073a4b0}, 0x1, 0xc00013c420)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000184660, 0x3b9aca00, 0x0, 0x0, 0x4537c5)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x0, 0xc000513768, 0xc000513778)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.22.6/pkg/util/wait/wait.go:90 +0x25
created by github.com/koordinator-sh/koordinator/pkg/koordlet/metricsadvisor.(*collector).Run
        /home/runner/work/koordinator/koordinator/pkg/koordlet/metricsadvisor/collector.go:133 +0x505
```

We added some log printing in the program：
```
processesInfos, ret := gpuDevice.Device.GetComputeRunningProcesses()
...
processUtilizations, ret := gpuDevice.Device.GetProcessUtilization(1024)
...
klog.V(3).Infof("Found %d processes %d processUtilizations on device %d\n", len(processesInfos), len(processUtilizations), deviceIndex)
for _, info := range processesInfos {
                        klog.V(3).Infof("Pid:%d,ComputeInstanceId:%d,GpuInstanceId:%d,UsedGpuMemory:%d\n", info.Pid, info.ComputeInstanceId, info.GpuInstanceId, info.UsedGpuMemory)
                }
for _, info := range processUtilizations {
                        klog.V(3).Infof("Pid:%d,DecUtil:%d,EncUtil:%d,MemUtil:%d,SmUtil:%d,TimeStamp:%d\n", info.Pid, info.DecUtil, info.EncUtil, info.MemUtil, info.SmUtil, info.TimeStamp)
                }
```
The logs obtained are as follows:
```
I1226 16:45:46.938826  101426 collector_gpu_linux.go:248] Found 5 processes 1 processUtilizations on device 0
I1226 16:45:46.938856  101426 collector_gpu_linux.go:250] Pid:34525,ComputeInstanceId:4294967295,GpuInstanceId:4294967295,UsedGpuMemory:846200832
I1226 16:45:46.938867  101426 collector_gpu_linux.go:250] Pid:74010,ComputeInstanceId:4294967295,GpuInstanceId:4294967295,UsedGpuMemory:2393899008
I1226 16:45:46.938877  101426 collector_gpu_linux.go:250] Pid:94284,ComputeInstanceId:4294967295,GpuInstanceId:4294967295,UsedGpuMemory:2349858816
I1226 16:45:46.938887  101426 collector_gpu_linux.go:250] Pid:94285,ComputeInstanceId:4294967295,GpuInstanceId:4294967295,UsedGpuMemory:2349858816
I1226 16:45:46.938896  101426 collector_gpu_linux.go:250] Pid:101019,ComputeInstanceId:4294967295,GpuInstanceId:4294967295,UsedGpuMemory:1768947712
I1226 16:45:46.938906  101426 collector_gpu_linux.go:254] Pid:94284,DecUtil:0,EncUtil:0,MemUtil:0,SmUtil:0,TimeStamp:1672044336412524
```
Please help to see what causes this.

**Comment by zwzhang0107** [comment]
PTAL @@jasonliu747

**Comment by LambdaHJ** [comment]
which version? @myl1024

**Comment by myl1024** [comment]
v1.0.0 @LambdaHJ

**Comment by LambdaHJ** [comment]
I can't reproduce your situation. Can you provide more information to help me reproduce your situation? For example, the cuda version, which programs run on the GPU, and so on. @myl1024

**Comment by zwzhang0107** [comment]
hi, any new information can be provided @myl1024

**Comment by zypln** [comment]
@LambdaHJ @zwzhang0107 I'm a colleague of myl1024。The host environment information of koordinator deployment is as follows：
os version: Kylin V10 SP1
kernel version: 4.19.90-23.15.v2101.ky10.x86_64
nvidia driver version: 470.129.06
nvidia CUDA version: 11.4

Otherwise，the koordlet is in a normal state after deployment. However, when any application using GPU resources is deployed on the GPU node, the koordlet on that node will crash and report the above error。

**Comment by jasonliu747** [comment]
@zypln @myl1024 Hi, unfortunately, @LambdaHJ and I really can't reproduce this issue. 😫😫😫
